{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "SQIP.serviceAccountName" . }}
  labels:
{{ include "SQIP.labels" . | nindent 4 }}
{{- end -}}
